sudo: required
dist: trusty
language: python
cache: apt

env:
  global:
    - secure: "ncdGAp+fZp2yqQVOOPozAuXjqmHbUasTIxNlqpbQXbG5kZvnCVdqxCsYb+2jupolUQ6g8ANgHEZnSz3tPCVB33JqDQLN8AQ0TdR6FzsFEARVHgmFpzpZbPh2gjJd9JRGfHgt0+2outnhQdEhwXfNxs+HsIR33G8WloHkVLhIWtc="
    - secure: "ZyCsnqo5ViDuqLHM+fPuKTG3SzAahZZxgzsqpOj6JKS+SvMgmeaK4F2RBYdOtsSI2Z2I9MpOvEOMZVaLf39mObz4si4c09PVkCnKYK4vTegobEdpR05Hx8AezgKffaLO6qGVm4EZSHu/PpdUYcDjdexI9Grp4Li//upSk3ynvp8="

matrix:
  include:
    - python: 2.7
      env:
        - UPLOAD_SDIST=1
    - python: 3.4
    - python: 3.5.1
    - python: 3.5.2
    - python: 3.5
      sudo: required
      services:
      - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_LINUX_WHEEL=1
    - python: 3.5
      sudo: required
      services:
      - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_LINUX_WHEEL=1 PRE_CMD=linux32
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=2.7.12
    - os: osx
      language: generic
      osx_image: xcode7.3 # 7.3 is OS X 10.11.x
      env:
        - PYENV=2.7.12
    - os: osx
      language: generic
      osx_image: xcode8.1 # 8.1 is macOS 10.12.x
      env:
        - PYENV=2.7.12
addons:
  apt:
    packages:
    - python-dev
    - libdwarf-dev
    - libelfg0-dev
    - libunwind8-dev

install:
  - if [[ "$BUILD_LINUX_WHEEL" == "1" ]]; then docker pull $DOCKER_IMAGE; fi
  - bash ./travis/install.sh

script:
  - py.test vmprof/ -vrs
  - py.test jitlog/ -vrs
  - if [[ "$BUILD_LINUX_WHEEL" == "1" ]]; then docker run --rm -v `pwd`:/io:Z $DOCKER_IMAGE
    $PRE_CMD bash /io/travis/build-wheels.sh; fi

after_success:
  - if [[ -n "TRAVIS_TAG" ]]; then bash travis/upload-artifact.sh; fi

notifications:
  irc:
    channels: irc.freenode.org#baroque-dev
    template:
    - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: change
