sudo: required
dist: trusty
language: python
cache: apt

env:
  global:
    - secure: "ncdGAp+fZp2yqQVOOPozAuXjqmHbUasTIxNlqpbQXbG5kZvnCVdqxCsYb+2jupolUQ6g8ANgHEZnSz3tPCVB33JqDQLN8AQ0TdR6FzsFEARVHgmFpzpZbPh2gjJd9JRGfHgt0+2outnhQdEhwXfNxs+HsIR33G8WloHkVLhIWtc="
    - secure: "ZyCsnqo5ViDuqLHM+fPuKTG3SzAahZZxgzsqpOj6JKS+SvMgmeaK4F2RBYdOtsSI2Z2I9MpOvEOMZVaLf39mObz4si4c09PVkCnKYK4vTegobEdpR05Hx8AezgKffaLO6qGVm4EZSHu/PpdUYcDjdexI9Grp4Li//upSk3ynvp8="

matrix:
  include:
    - python: 2.7
      services:
        - docker
      env:
        - BUILD_LINUX_WHEEL=1 UPLOAD_SDIST=1
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=2.7.13 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=3.4.6 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=3.5.3 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=3.6.1 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode7.3 # 7.3 is OS X 10.11.x
      env:
        - PYENV=3.5.3
    - os: osx
      language: generic
      osx_image: xcode8.2 # 8.2 is macOS 10.12.x
      env:
        - PYENV=3.5.3
    - os: osx
      language: generic
      osx_image: xcode8.2 # 8.2 is macOS 10.12.x
      env:
        - PYENV=3.6.1
addons:
  apt:
    packages:
    - python-dev
    - libdwarf-dev
    - libelfg0-dev
    - libunwind8-dev
    - wget

install:
  - bash ./travis/install.sh

script:
  - bash ./travis/script.sh

notifications:
  irc:
    channels: irc.freenode.org#baroque-dev
    template:
    - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: change
