language: python
sudo: false
python:
  - 2.7
  - 3.4

cache: apt

# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y python-dev
#   - sudo apt-get install -y libelfg0-dev
#   - sudo apt-get install -y libunwind8-dev

addons:
  apt:
    packages:
    - python-dev
    - libelfg0-dev
    - libunwind8-dev
    - libdwarf-dev

install:
  - pip install .

script:
  - py.test tests/ -v

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
