sudo: required
dist: trusty

cache: apt

matrix:
  include:
    # linux
    - python: 2.7
    - python: 3.4
    - python: 3.5.1
    - python: 3.5.2
    - python: nightly
    - language: generic
      os: osx
      # see: https://docs.travis-ci.com/user/osx-ci-environment/
      osx_image: xcode8.1 # 8.1 is macOS 10.12.x
      env: CPYTHON=py27
    - language: generic
      os: osx
      osx_image: xcode7.3 # 7.3 is OS X 10.11.x
      env: CPYTHON=py27
    - language: generic
      os: osx
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env: CPYTHON=py27
    # build linux wheels
    - python: 3.5
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_LINUX_WHEEL=1
    - python: 3.5
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_LINUX_WHEEL=1
           PRE_CMD=linux32

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y libdwarf-dev
  - sudo apt-get install -y libelfg0-dev
  - sudo apt-get install -y libunwind8-dev

install:
  - test "$BUILD_LINUX_WHEEL" = "1" && docker pull $DOCKER_IMAGE
  - pip install .

script:
  - py.test vmprof/ -vrs
  - py.test jitlog/ -vrs
  - test "$BUILD_LINUX_WHEEL" = "1" &&
         docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD
                                      /io/travis/build-wheels.sh
  - test "$BUILD_LINUX_WHEEL" = "1" &&
         ls wheels

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
