sudo: required
dist: trusty
language: python
cache: apt

env:
  # pypi
  - secure: "ncdGAp+fZp2yqQVOOPozAuXjqmHbUasTIxNlqpbQXbG5kZvnCVdqxCsYb+2jupolUQ6g8ANgHEZnSz3tPCVB33JqDQLN8AQ0TdR6FzsFEARVHgmFpzpZbPh2gjJd9JRGfHgt0+2outnhQdEhwXfNxs+HsIR33G8WloHkVLhIWtc="
  # pypi
  - secure: "ZyCsnqo5ViDuqLHM+fPuKTG3SzAahZZxgzsqpOj6JKS+SvMgmeaK4F2RBYdOtsSI2Z2I9MpOvEOMZVaLf39mObz4si4c09PVkCnKYK4vTegobEdpR05Hx8AezgKffaLO6qGVm4EZSHu/PpdUYcDjdexI9Grp4Li//upSk3ynvp8="
  # github token
  - secure: "gHckGVHSQq95lbF7/KS6wA65VF+PR89u0dkHuEf008CcXlhLV3KW4dcmrJj4/bsfYgFyfPHmCRth2v3U1rx+TP+NvZ2kUFLAYLsySIHDv7Q2IfzQDG8RgHm/FL91PVS/novOoKQ10We0HedQhqejICuElwIaEQh44WZIMaU/SiI="


matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5.1
  - python: 3.5.2
  - python: nightly
  - python: 3.5
    sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_LINUX_WHEEL=1
  - python: 3.5
    sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_LINUX_WHEEL=1 PRE_CMD=linux32
    # TODO, activate mac
      # - language: generic
      # - os: osx
      # - # see: https://docs.travis-ci.com/user/osx-ci-environment/
      # - osx_image: xcode8.1 # 8.1 is macOS 10.12.x
      # - env: CPYTHON=py27
    # - language: generic
      # - os: osx
      # - osx_image: xcode7.3 # 7.3 is OS X 10.11.x
      # - env: CPYTHON=py27
    # - language: generic
      # - os: osx
      # - osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      # - env: CPYTHON=py27
      #
addons:
  apt:
    packages:
    - python-dev
    - libdwarf-dev
    - libelfg0-dev
    - libunwind8-dev

install:
- if [[ "$BUILD_LINUX_WHEEL" == "1" ]]; then docker pull $DOCKER_IMAGE; fi
- pip install .
script:
- py.test vmprof/ -vrs
- py.test jitlog/ -vrs
- if [[ "$BUILD_LINUX_WHEEL" == "1" ]]; then docker run --rm -v `pwd`:/io:Z $DOCKER_IMAGE
  $PRE_CMD bash /io/travis/build-wheels.sh; fi

deploy:
  provider: script
  script: travis/upload-artifact.sh
  on:
    tags: true

notifications:
  irc:
    channels: irc.freenode.org#baroque-dev
    template:
    - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: change
