sudo: required
dist: trusty
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.5.1
  - 3.5.2
  - nightly

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:

cache: apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y libdwarf-dev
  - sudo apt-get install -y libelfg0-dev
  - sudo apt-get install -y libunwind8-dev

install:
  - pip install .

script:
  - py.test vmprof/ -vrs
  - py.test jitlog/ -vrs
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
