sudo: required
dist: trusty
language: python
cache: apt

env:
  global:
    - PYPI_USERNAME=pypy.wheelbuilder

    # PYPI_PASSWORD
    - secure: "a5GdswXPW9TWytW5BfA5QZkdyrzgebecUNcbEmEXYkGPGp7rTFKVnRShD8+9YqH7swaZi9Xz/4YzBrZIkcXS0M+FJPo9sGYIccobZQ+KAlqbIE3N7cuWNLStqJDAj41BK9xxDtdKutJ95q+8iO9BLx+Iw6Y62EN4+a4d3WbuoZ4="

matrix:
  include:
    - python: 2.7
      services:
        - docker
      env:
        - BUILD_LINUX_WHEEL=1 UPLOAD_SDIST=1
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=2.7.13 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=3.6.9 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=3.7.5 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode6.4 # 6.4 is OS X 10.10.x
      env:
        - PYENV=3.8.0 MAC_WHEEL=1
    - os: osx
      language: generic
      osx_image: xcode7.3 # 7.3 is OS X 10.11.x
      env:
        - PYENV=3.8.0
    - os: osx
      language: generic
      osx_image: xcode8.2 # 8.2 is macOS 10.12.x
      env:
        - PYENV=3.8.0
    - os: osx
      language: generic
      osx_image: xcode8.2 # 8.2 is macOS 10.12.x
      env:
        - PYENV=3.8.0
addons:
  apt:
    packages:
    - python-dev
    - libdwarf-dev
    - libelfg0-dev
    - libunwind8-dev

install:
  - bash ./travis/install.sh

script:
  - bash ./travis/script.sh

notifications:
  irc:
    channels: irc.freenode.org#pypy
    template:
    - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: change
