language: python

python:
  - 2.7
  - 3.4

sudo: false

addons:
  apt:
    packages:
    - python-dev
    - libelf-dev
    - libunwind8-dev

install:
  - pip install .

script:
  - py.test tests/ -vrs

# notifications:
#   irc:
#     channels: "irc.freenode.org#baroque-dev"
#     template:
#       - "%{repository}@%{branch}: %{message} (%{build_url})"
#     use_notice: true
#     on_success: always
#     on_failure: always

#   email:
#     on_success: change
#     on_failure: change
